name: eLEDglance
favicon: null
layout_spectrum: 0.2394604
typography_spectrum: 0.744019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e77817'
    - '#00923f'
    - '#4c4846'
    - '#f4c59c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
