name: eLEDglance
favicon: null
layout_spectrum: 0.2394604
typography_spectrum: 0.744019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#6D6E70'
    - '#1F1F1F'
    - '#0203FF'
    - '#01FF01'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
